name: Publish
on:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        channel:
          - latest
          - dev

    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.4.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Build Types
        run: pnpm types
      - name: Set NPMRC
        run: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Release to @dev channel
        if: matrix.channel == 'dev'
        run: |
          pnpm version:snapshot
          pnpm run publish:beta
      - name: Publish
        if: matrix.channel == 'latest'
        run: |
          pnpm run publish
      - name: Push tags
        if: matrix.channel == 'latest'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          pnpm push-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Create release pull request
        uses: changesets/action@v1
        if: matrix.channel == 'latest'
        with:
          version: pnpm run version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # check to see if there are any deleted files in the .changeset folder and outputs yes or no to be used in the next job
  check-changeset-folder:
    name: Check changeset folder
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      # Uses tj-actions/changed-files to get a list of changed files in the .changeset folder
      # See docs here: https://github.com/tj-actions/changed-files
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: .changeset/**
      # Sets the output
      # any_deleted is populated by @tj-actions/changed-files and is a boolean. True if there are any deleted files, false if there are not.
      - id: set
        run: |
          if ${{ steps.changed-files.outputs.any_deleted }}; then
           echo "run_job=yes" >> $GITHUB_OUTPUT
          else
            echo "run_job=no" >> $GITHUB_OUTPUT
          fi
    outputs:
      run_job: ${{ steps.set.outputs.run_job }}

  update-repos:
    needs:
      - check-changeset-folder
      - build
    # Only run this job if the check-changeset-folder job outputs yes
    if: needs.check-changeset-folder.outputs.run_job == 'yes'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['tinacms/tina-cloud-starter', 'tinacms/tina-barebones-starter']
    steps:
      # Clone repo
      - name: Check out repo to update
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.repo }}
          token: ${{ secrets.TINA_GH_TOKEN }}
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      # Install deps, update Tina packages, update schema, and create a pull request
      - name: Install dependencies
        run: yarn install
      - name: Update Tina packages
        run: yarn upgrade tinacms@latest @tinacms/cli@latest
      - name: Update Schema
        run: yarn tinacms audit
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.TINA_GH_TOKEN }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          delete-branch: true
          commit-message: Update Tina packages
          title: Update Tina packages
          body: |
            This PR was automatically created by a GitHub action.
            Please review this PR and merge it if it looks good.
          branch-suffix: timestamp
