name: Publish
on:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        channel:
          - latest
          - dev

    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.4.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Build Types
        run: pnpm types
      - name: Set NPMRC
        run: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Release to @dev channel
        if: matrix.channel == 'dev'
        run: |
          pnpm version:snapshot
          pnpm run publish:beta
      - name: Publish
        if: matrix.channel == 'latest'
        run: |
          pnpm run publish
      - name: Push tags
        if: matrix.channel == 'latest'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          pnpm push-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Create release pull request
        uses: changesets/action@v1
        if: matrix.channel == 'latest'
        with:
          version: pnpm run version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  check-changeset-folder:
    needs: build
    name: a
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Check if a file has been deleted from the .changeset folder
      - id: set
        run: |
          deleted_file=$(git diff-tree --no-commit-id --name-only -r HEAD | grep ".changeset/")
          if [ -n "$deleted_file" ]; then
             echo "::set-output name=run_job::yes"
          else
            echo "::set-output name=run_job::no"
          fi
    outputs:
      run_job: ${{ steps.set.outputs.run_job }}

  update-repos:
    needs:
      - check-changeset-folder
      - build
    if: needs.check-changeset-folder.outputs.run_job == 'yes'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['tinacms/tina-cloud-starter', 'tinacms/tina-barebones-starter']
    steps:
      - name: Check out repo to update
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.repo }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Update Tina packages
        run: yarn upgrade tinacms@latest @tinacms/cli@latest
      - name: Update Schema
        run: yarn tinacms audit
      - name: Create and switch to new branch
        run: |
          current_date=$(date +"%Y-%m-%d")
          branch_name="update-tina-$current_date"
          git checkout -b $branch_name
      - name: Commit and push changes
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "Update from action"
          git push origin $branch_name
      - name: Create pull request
        uses: actions/create-pull-request@v2
        with:
          title: 'Update from action'
          head: $branch_name
          base: main
          body: 'This pull request was automatically created by a GitHub action.'
          repository: ${{ matrix.repo }}
          token: ${{ secrets.GITHUB_TOKEN }}
